In [51]:
import numpy as np
import pandas as pd

In [52]:
product_df = pd.DataFrame(
    {'product_id': range(5),
     'product': ['dairy', 'dairy', 'dairy', 'vegetables', 'fruits'],
     'price': [2.56, 2.56, 4.55, 2.74, 5.44]}
)
product_df

   product_id     product  price
0           0       dairy   2.56
1           1       dairy   2.56
2           2       dairy   4.55
3           3  vegetables   2.74
4           4      fruits   5.44

In [53]:
mapping_dict = {'dairy': 'non_vegan', 'vegetables': 'vegan', 'fruits': 'vegan'}
product_df['vegan?'] = product_df['product'].map(mapping_dict)
product_df

   product_id     product  price     vegan?
0           0       dairy   2.56  non_vegan
1           1       dairy   2.56  non_vegan
2           2       dairy   4.55  non_vegan
3           3  vegetables   2.74      vegan
4           4      fruits   5.44      vegan

In [54]:
product_map = {'dairy': 0, 'vegetables': 1, 'fruits': 2}
vegan_map = {'non_vegan': 0, 'vegan': 1}
product_df['product'] = product_df['product'].map(product_map).astype('int')
product_df['vegan?'] = product_df['vegan?'].map(vegan_map).astype('int')
product_df

   product_id  product  price  vegan?
0           0        0   2.56       0
1           1        0   2.56       0
2           2        0   4.55       0
3           3        1   2.74       1
4           4        2   5.44       1

In [55]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  5 non-null      int64
 1   product     5 non-null      int64
 2   price       5 non-null      float64
 3   vegan?      5 non-null      int64
dtypes: float64(1), int64(3)
memory usage: 292.0 bytes

In [56]:
product_df.corr()

            product_id   product     price    vegan?
product_id    1.000000  0.883883  0.700698  0.866025
product       0.883883  1.000000  0.606823  0.918559
price         0.700698  0.606823  1.000000  0.354150
vegan?        0.866025  0.918559  0.354150  1.000000

In [57]:
product_df['price'] = product_df['price'].map(lambda x: f"${x}")
product_df

   product_id  product  price  vegan?
0           0        0  $2.56       0
1           1        0  $2.56       0
2           2        0  $4.55       0
3           3        1  $2.74       1
4           4        2  $5.44       1

In [58]:
product_df['price'] = product_df['price'].apply(lambda x: f"{x} dollars")
product_df

   product_id  product          price  vegan?
0           0        0  $2.56 dollars       0
1           1        0  $2.56 dollars       0
2           2        0  $4.55 dollars       0
3           3        1  $2.74 dollars       1
4           4        2  $5.44 dollars       1

In [59]:
product_df['price'] = product_df['price'].map(lambda x: x[1:5])
product_df

   product_id  product price  vegan?
0           0        0  2.56       0
1           1        0  2.56       0
2           2        0  4.55       0
3           3        1  2.74       1
4           4        2  5.44       1

In [62]:
retail = pd.read_csv('./assets/retail.csv')
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [63]:
retail.loc[:, 'family'].value_counts()

family
AUTOMOTIVE                    31968
BABY CARE                     31968
BEAUTY                        31968
BEVERAGES                     31968
BOOKS                         31968
BREAD/BAKERY                  31968
CELEBRATION                   31968
CLEANING                      31968
DAIRY                         31968
DELI                          31968
EGGS                          31968
FROZEN FOODS                  31968
GROCERY I                     31968
GROCERY II                    31968
HARDWARE                      31968
HOME AND KITCHEN I            31968
HOME AND KITCHEN II           31968
HOME APPLIANCES               31968
HOME CARE                     31968
LADIESWEAR                    31968
LAWN AND GARDEN               31968
LINGERIE                      31968
LIQUOR,WINE,BEER              31968
MAGAZINES                     31968
MEATS                         31968
PERSONAL CARE                 31968
PET SUPPLIES                  31968
PLAYERS AND ELECTRONICS       31968
POULTRY                       31968
PREPARED FOODS                31968
PRODUCE                       31968
SCHOOL AND OFFICE SUPPLIES    31968
SEAFOOD                       31968
Name: count, dtype: int64

In [70]:
product_category_dict = {
    'PRODUCE': 'Grocery',
    'POULTRY': 'Grocery',
    'GROCERY I': 'Grocery',
    'GROCERY II': 'Grocery',
    'EGGS': 'Grocery'
}
retail['family'].map(product_category_dict).value_counts(dropna=False)

family
NaN        895104
Grocery    159840
Name: count, dtype: int64