In [18]:
import numpy as np
import pandas as pd

In [19]:
pd.DataFrame(
    {'id': [1, 2],
     'store_nbr': [1, 2],
     'family': ['POULTRY', 'PRODUCE']
    }
)

   id  store_nbr   family
0   1          1  POULTRY
1   2          2  PRODUCE

In [20]:
retail_df = pd.read_csv('./assets/retail.csv')
retail_df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [21]:
oil = pd.read_csv('./assets/oil.csv')
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [22]:
oil.shape

(1218, 2)

In [23]:
oil.axes

[RangeIndex(start=0, stop=1218, step=1),
 Index(['date', 'dcoilwtico'], dtype='str')]

In [24]:
oil.index

RangeIndex(start=0, stop=1218, step=1)

In [25]:
oil.columns

Index(['date', 'dcoilwtico'], dtype='str')

In [26]:
oil.size

2436

In [27]:
oil.columns = ['price_date', 'oil_price']
oil.columns

Index(['price_date', 'oil_price'], dtype='str')

In [28]:
oil.dtypes

price_date        str
oil_price     float64
dtype: object

In [29]:
retail_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  str
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  str
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), str(2)
memory usage: 48.3 MB

In [30]:
retail_df.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  str
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  str
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), str(2)
memory usage: 48.3 MB

In [31]:
retail_df.describe()

                 id     store_nbr         sales   onpromotion
count  1.054944e+06  1.054944e+06  1.054944e+06  1.054944e+06
mean   2.473416e+06  2.750000e+01  4.577225e+02  5.937977e+00
std    3.045362e+05  1.558579e+01  1.317155e+03  1.808632e+01
min    1.945944e+06  1.000000e+00  0.000000e+00  0.000000e+00
25%    2.209680e+06  1.400000e+01  2.000000e+00  0.000000e+00
50%    2.473416e+06  2.750000e+01  2.400000e+01  0.000000e+00
75%    2.737151e+06  4.100000e+01  2.620000e+02  3.000000e+00
max    3.000887e+06  5.400000e+01  1.247170e+05  7.410000e+02

In [32]:
retail_df.describe(include='all').round()

               id        date  store_nbr      family      sales  onpromotion
count   1054944.0     1054944  1054944.0     1054944  1054944.0    1054944.0
unique        NaN         592        NaN          33        NaN          NaN
top           NaN  2016-01-01        NaN  AUTOMOTIVE        NaN          NaN
freq          NaN        1782        NaN       31968        NaN          NaN
mean    2473416.0         NaN       28.0         NaN      458.0          6.0
std      304536.0         NaN       16.0         NaN     1317.0         18.0
min     1945944.0         NaN        1.0         NaN        0.0          0.0
25%     2209680.0         NaN       14.0         NaN        2.0          0.0
50%     2473416.0         NaN       28.0         NaN       24.0          0.0
75%     2737151.0         NaN       41.0         NaN      262.0          3.0
max     3000887.0         NaN       54.0         NaN   124717.0        741.0

In [34]:
oil.head(10)

   price_date  oil_price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20
5  2013-01-08      93.21
6  2013-01-09      93.08
7  2013-01-10      93.81
8  2013-01-11      93.60
9  2013-01-14      94.27

In [38]:
oil.tail(10)

      price_date  oil_price
1208  2017-08-18      48.59
1209  2017-08-21      47.39
1210  2017-08-22      47.65
1211  2017-08-23      48.45
1212  2017-08-24      47.24
1213  2017-08-25      47.65
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26

In [42]:
oil.sample(5)

     price_date  oil_price
253  2013-12-20      99.11
796  2016-01-20      26.68
520  2014-12-30      54.14
491  2014-11-19      74.55
238  2013-11-29      92.55

In [43]:
oil.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price_date  1218 non-null   str
 1   oil_price   1175 non-null   float64
dtypes: float64(1), str(1)
memory usage: 19.2 KB

In [44]:
oil.describe()

         oil_price
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
25%      46.405000
50%      53.190000
75%      95.660000
max     110.620000

In [45]:
oil.describe(include='all')

        price_date    oil_price
count         1218  1175.000000
unique        1218          NaN
top     2013-01-01          NaN
freq             1          NaN
mean           NaN    67.714366
std            NaN    25.630476
min            NaN    26.190000
25%            NaN    46.405000
50%            NaN    53.190000
75%            NaN    95.660000
max            NaN   110.620000