In [81]:
import numpy as np
import pandas as pd

In [82]:
retail_df = pd.read_csv('./assets/retail.csv')
retail_df.iloc[:5]

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [83]:
oil = pd.read_csv('./assets/oil.csv')
oil.columns = ['date', 'price']
oil.head()

         date  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [84]:
retail_df['family']

0                          AUTOMOTIVE
1                           BABY CARE
2                              BEAUTY
3                           BEVERAGES
4                               BOOKS
                      ...
1054939                       POULTRY
1054940                PREPARED FOODS
1054941                       PRODUCE
1054942    SCHOOL AND OFFICE SUPPLIES
1054943                       SEAFOOD
Name: family, Length: 1054944, dtype: str

In [85]:
retail_df.family

0                          AUTOMOTIVE
1                           BABY CARE
2                              BEAUTY
3                           BEVERAGES
4                               BOOKS
                      ...
1054939                       POULTRY
1054940                PREPARED FOODS
1054941                       PRODUCE
1054942    SCHOOL AND OFFICE SUPPLIES
1054943                       SEAFOOD
Name: family, Length: 1054944, dtype: str

In [86]:
retail_df['family'].nunique()

33

In [87]:
retail_df['family'].value_counts().iloc[:5]

family
AUTOMOTIVE    31968
BABY CARE     31968
BEAUTY        31968
BEVERAGES     31968
BOOKS         31968
Name: count, dtype: int64

In [88]:
retail_df['sales'].mean()

np.float64(457.72248700136424)

In [89]:
retail_df['sales'].sum().round()

np.float64(482871591.0)

In [90]:
retail_df[['family', 'store_nbr']].iloc[:5]

       family  store_nbr
0  AUTOMOTIVE          1
1   BABY CARE          1
2      BEAUTY          1
3   BEVERAGES          1
4       BOOKS          1

In [91]:
oil.date.head()

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
4    2013-01-07
Name: date, dtype: str

In [92]:
oil.loc[:,'price'].head()

0      NaN
1    93.14
2    92.97
3    93.12
4    93.20
Name: price, dtype: float64

In [93]:
oil['price'].head()

0      NaN
1    93.14
2    92.97
3    93.12
4    93.20
Name: price, dtype: float64

In [94]:
oil[['price']].head()

   price
0    NaN
1  93.14
2  92.97
3  93.12
4  93.20

In [95]:
oil[['price', 'date']].head()

   price        date
0    NaN  2013-01-01
1  93.14  2013-01-02
2  92.97  2013-01-03
3  93.12  2013-01-04
4  93.20  2013-01-07

In [96]:
retail_df.iloc[:5]

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [97]:
retail_df.iloc[:5, :]

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [98]:
retail_df.iloc[:, 1:4].sample(5)

              date  store_nbr                      family
714382  2017-02-05         52  SCHOOL AND OFFICE SUPPLIES
487604  2016-09-30          4              PREPARED FOODS
563610  2016-11-12         23                   BEVERAGES
189605  2016-04-16         29             LAWN AND GARDEN
82565   2016-02-16         25                     SEAFOOD

In [99]:
retail_df.iloc[:5, 1:5]

         date  store_nbr      family  sales
0  2016-01-01          1  AUTOMOTIVE    0.0
1  2016-01-01          1   BABY CARE    0.0
2  2016-01-01          1      BEAUTY    0.0
3  2016-01-01          1   BEVERAGES    0.0
4  2016-01-01          1       BOOKS    0.0

In [100]:
retail_df.loc[:, 'date']

0          2016-01-01
1          2016-01-01
2          2016-01-01
3          2016-01-01
4          2016-01-01
              ...
1054939    2017-08-15
1054940    2017-08-15
1054941    2017-08-15
1054942    2017-08-15
1054943    2017-08-15
Name: date, Length: 1054944, dtype: str

In [101]:
retail_df.loc[:, 'date'].value_counts()

date
2016-01-01    1782
2016-01-02    1782
2016-01-03    1782
2016-01-04    1782
2016-01-05    1782
              ...
2017-08-11    1782
2017-08-12    1782
2017-08-13    1782
2017-08-14    1782
2017-08-15    1782
Name: count, Length: 592, dtype: int64

In [102]:
retail_df.loc[:, 'date'].value_counts().nunique()

1

In [103]:
retail_df.loc[:, ['date']]

               date
0        2016-01-01
1        2016-01-01
2        2016-01-01
3        2016-01-01
4        2016-01-01
...             ...
1054939  2017-08-15
1054940  2017-08-15
1054941  2017-08-15
1054942  2017-08-15
1054943  2017-08-15

[1054944 rows x 1 columns]

In [104]:
retail_df.loc[:, ['date', 'sales']]

               date     sales
0        2016-01-01     0.000
1        2016-01-01     0.000
2        2016-01-01     0.000
3        2016-01-01     0.000
4        2016-01-01     0.000
...             ...       ...
1054939  2017-08-15   438.133
1054940  2017-08-15   154.553
1054941  2017-08-15  2419.729
1054942  2017-08-15   121.000
1054943  2017-08-15    16.000

[1054944 rows x 2 columns]

In [105]:
retail_df.loc[:, 'date':'sales']

               date  store_nbr                      family     sales
0        2016-01-01          1                  AUTOMOTIVE     0.000
1        2016-01-01          1                   BABY CARE     0.000
2        2016-01-01          1                      BEAUTY     0.000
3        2016-01-01          1                   BEVERAGES     0.000
4        2016-01-01          1                       BOOKS     0.000
...             ...        ...                         ...       ...
1054939  2017-08-15          9                     POULTRY   438.133
1054940  2017-08-15          9              PREPARED FOODS   154.553
1054941  2017-08-15          9                     PRODUCE  2419.729
1054942  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES   121.000
1054943  2017-08-15          9                     SEAFOOD    16.000

[1054944 rows x 4 columns]

In [106]:
oil['euro_price'] = oil['price'] * 1.1
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [107]:
oil.iloc[:10]

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531
6  2013-01-09  93.08     102.388
7  2013-01-10  93.81     103.191
8  2013-01-11  93.60     102.960
9  2013-01-14  94.27     103.697

In [108]:
oil.iloc[:10, :]

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531
6  2013-01-09  93.08     102.388
7  2013-01-10  93.81     103.191
8  2013-01-11  93.60     102.960
9  2013-01-14  94.27     103.697

In [ ]:
oil.iloc[:, -1]

      euro_price
0            NaN
1        102.454
2        102.267
3        102.432
4        102.520
...          ...
1213      52.415
1214      51.040
1215      51.106
1216      50.556
1217      51.986

[1218 rows x 1 columns]

In [111]:
oil.iloc[:, [-1]]

      euro_price
0            NaN
1        102.454
2        102.267
3        102.432
4        102.520
...          ...
1213      52.415
1214      51.040
1215      51.106
1216      50.556
1217      51.986

[1218 rows x 1 columns]

In [113]:
oil.iloc[:, -2:]

      price  euro_price
0       NaN         NaN
1     93.14     102.454
2     92.97     102.267
3     93.12     102.432
4     93.20     102.520
...     ...         ...
1213  47.65      52.415
1214  46.40      51.040
1215  46.46      51.106
1216  45.96      50.556
1217  47.26      51.986

[1218 rows x 2 columns]

In [114]:
oil.loc[:5]

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531

In [115]:
oil.loc[:5, 'date']

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
4    2013-01-07
5    2013-01-08
Name: date, dtype: str

In [117]:
oil.loc[:5, ['date', 'euro_price']]

         date  euro_price
0  2013-01-01         NaN
1  2013-01-02     102.454
2  2013-01-03     102.267
3  2013-01-04     102.432
4  2013-01-07     102.520
5  2013-01-08     102.531

In [118]:
oil.loc[:5, ['euro_price', 'date']]

   euro_price        date
0         NaN  2013-01-01
1     102.454  2013-01-02
2     102.267  2013-01-03
3     102.432  2013-01-04
4     102.520  2013-01-07
5     102.531  2013-01-08

In [119]:
oil.loc[:5, 'date':'euro_price']

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531