In [1]:
import numpy as np
import pandas as pd

In [4]:
retail_df = pd.read_csv('./assets/retail.csv')
retail_df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [8]:
retail_df.drop('id', axis=1).head()

         date  store_nbr      family  sales  onpromotion
0  2016-01-01          1  AUTOMOTIVE    0.0            0
1  2016-01-01          1   BABY CARE    0.0            0
2  2016-01-01          1      BEAUTY    0.0            0
3  2016-01-01          1   BEVERAGES    0.0            0
4  2016-01-01          1       BOOKS    0.0            0

In [10]:
retail_df.drop(['id', 'onpromotion'], axis=1).head()

         date  store_nbr      family  sales
0  2016-01-01          1  AUTOMOTIVE    0.0
1  2016-01-01          1   BABY CARE    0.0
2  2016-01-01          1      BEAUTY    0.0
3  2016-01-01          1   BEVERAGES    0.0
4  2016-01-01          1       BOOKS    0.0

In [13]:
retail_df.drop(0, axis=0).head()

        id        date  store_nbr        family  sales  onpromotion
1  1945945  2016-01-01          1     BABY CARE    0.0            0
2  1945946  2016-01-01          1        BEAUTY    0.0            0
3  1945947  2016-01-01          1     BEVERAGES    0.0            0
4  1945948  2016-01-01          1         BOOKS    0.0            0
5  1945949  2016-01-01          1  BREAD/BAKERY    0.0            0

In [15]:
retail_df.drop(0, axis=0).reset_index(drop=True).head()

        id        date  store_nbr        family  sales  onpromotion
0  1945945  2016-01-01          1     BABY CARE    0.0            0
1  1945946  2016-01-01          1        BEAUTY    0.0            0
2  1945947  2016-01-01          1     BEVERAGES    0.0            0
3  1945948  2016-01-01          1         BOOKS    0.0            0
4  1945949  2016-01-01          1  BREAD/BAKERY    0.0            0

In [18]:
oil = pd.read_csv('./assets/oil.csv')
oil.columns = ['date', 'price']
oil['euro_price'] = oil['price'] * 1.1
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [24]:
oil_euro = oil.drop('price', axis=1)
oil_euro.head()

         date  euro_price
0  2013-01-01         NaN
1  2013-01-02     102.454
2  2013-01-03     102.267
3  2013-01-04     102.432
4  2013-01-07     102.520

In [25]:
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [27]:
oil.drop(0, axis=0).head()

         date  price  euro_price
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531

In [29]:
oil.drop(0, axis=0).reset_index()

      index        date  price  euro_price
0         1  2013-01-02  93.14     102.454
1         2  2013-01-03  92.97     102.267
2         3  2013-01-04  93.12     102.432
3         4  2013-01-07  93.20     102.520
4         5  2013-01-08  93.21     102.531
...     ...         ...    ...         ...
1212   1213  2017-08-25  47.65      52.415
1213   1214  2017-08-28  46.40      51.040
1214   1215  2017-08-29  46.46      51.106
1215   1216  2017-08-30  45.96      50.556
1216   1217  2017-08-31  47.26      51.986

[1217 rows x 4 columns]