In [1]:
import numpy as np
import pandas as pd

In [3]:
product_df = pd.DataFrame(
    {'product': ['dairy', 'dairy', 'dairy', 'vegetables', 'fruits'],
     'price': [2.56, 2.56, 4.55, 2.74, 5.44]}
)
product_df

      product  price
0       dairy   2.56
1       dairy   2.56
2       dairy   4.55
3  vegetables   2.74
4      fruits   5.44

In [5]:
product_df.shape

(5, 2)

In [6]:
product_df.nunique()

product    3
price      4
dtype: int64

In [7]:
product_df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [8]:
product_df.duplicated(subset='product')

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [16]:
product_df.duplicated(subset='price', keep='last')

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [12]:
product_df.drop_duplicates()

      product  price
0       dairy   2.56
2       dairy   4.55
3  vegetables   2.74
4      fruits   5.44

In [15]:
product_df.drop_duplicates(subset='price')

      product  price
0       dairy   2.56
2       dairy   4.55
3  vegetables   2.74
4      fruits   5.44

In [22]:
product_df.drop_duplicates(subset='product', keep='last', ignore_index=True)

      product  price
0       dairy   4.55
1  vegetables   2.74
2      fruits   5.44

In [32]:
oil = pd.read_csv('./assets/oil.csv')
oil.columns = ['date', 'price']
oil['euro_price'] = oil['price'] * 1.1
oil.tail()

            date  price  euro_price
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

In [36]:
oil = pd.concat([oil, oil.iloc[[-1]]])
oil.tail()

            date  price  euro_price
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986
1217  2017-08-31  47.26      51.986

In [37]:
oil.shape

(1219, 3)

In [39]:
oil.nunique()

date          1218
price          998
euro_price     998
dtype: int64

In [40]:
oil.duplicated().sum()

np.int64(1)

In [41]:
oil.duplicated(subset='price').sum()

np.int64(220)

In [42]:
oil.drop_duplicates()

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [44]:
oil.drop_duplicates(keep='last')

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [45]:
oil.drop_duplicates(keep='last', ignore_index=True)

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [46]:
oil.drop_duplicates(subset=['price'], keep='first', ignore_index=True)

           date  price  euro_price
0    2013-01-01    NaN         NaN
1    2013-01-02  93.14     102.454
2    2013-01-03  92.97     102.267
3    2013-01-04  93.12     102.432
4    2013-01-07  93.20     102.520
..          ...    ...         ...
994  2017-08-15  47.57      52.327
995  2017-08-18  48.59      53.449
996  2017-08-21  47.39      52.129
997  2017-08-30  45.96      50.556
998  2017-08-31  47.26      51.986

[999 rows x 3 columns]