In [1]:
import numpy as np
import pandas as pd

In [17]:
product_df = pd.DataFrame(
    {'product': [pd.NA, 'Dairy', 'Dairy', pd.NA, 'Fruits'],
     'price': [2.56, pd.NA, 4.55, 2.74, pd.NA],
     'product_id': [1, 2, 3, 4, 5]}
)
product_df

  product price  product_id
0     NaN  2.56           1
1   Dairy  <NA>           2
2   Dairy  4.55           3
3     NaN  2.74           4
4  Fruits  <NA>           5

In [18]:
product_df.isna()

   product  price  product_id
0     True  False       False
1    False   True       False
2    False  False       False
3     True  False       False
4    False   True       False

In [19]:
product_df.isna().sum()

product       2
price         2
product_id    0
dtype: int64

In [26]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     3 non-null      str
 1   price       3 non-null      object
 2   product_id  5 non-null      int64
dtypes: int64(1), object(1), str(1)
memory usage: 269.0+ bytes

In [27]:
product_df.fillna(0)

  product price  product_id
0       0  2.56           1
1   Dairy     0           2
2   Dairy  4.55           3
3       0  2.74           4
4  Fruits     0           5

In [28]:
product_df.fillna({'price': 0})

  product price  product_id
0     NaN  2.56           1
1   Dairy     0           2
2   Dairy  4.55           3
3     NaN  2.74           4
4  Fruits     0           5

In [29]:
product_df.dropna()

  product price  product_id
2   Dairy  4.55           3

In [37]:
product_df.dropna(subset='price')
product_df.dropna(subset=['price'])

  product price  product_id
0     NaN  2.56           1
2   Dairy  4.55           3
3     NaN  2.74           4