In [1]:
import numpy as np
import pandas as pd

In [8]:
retail_df = pd.read_csv('./assets/retail.csv')
retail_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  str
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  str
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), str(2)
memory usage: 69.2 MB

In [14]:
mask = retail_df['date'] == '2016-10-28'
retail_df.loc[mask]

,id,date,store_nbr,family,sales,onpromotion
536382,2482326,2016-10-28,1,AUTOMOTIVE,8.000,0
536383,2482327,2016-10-28,1,BABY CARE,0.000,0
536384,2482328,2016-10-28,1,BEAUTY,9.000,1
536385,2482329,2016-10-28,1,BEVERAGES,2576.000,38
536386,2482330,2016-10-28,1,BOOKS,0.000,0
...,...,...,...,...,...,...
538159,2484103,2016-10-28,9,POULTRY,391.292,24
538160,2484104,2016-10-28,9,PREPARED FOODS,78.769,1
538161,2484105,2016-10-28,9,PRODUCE,993.760,5
538162,2484106,2016-10-28,9,SCHOOL AND OFFICE SUPPLIES,0.000,0
538163,2484107,2016-10-28,9,SEAFOOD,3.000,1

In [16]:
retail_df.loc[mask, ['date', 'sales']]

              date     sales
536382  2016-10-28     8.000
536383  2016-10-28     0.000
536384  2016-10-28     9.000
536385  2016-10-28  2576.000
536386  2016-10-28     0.000
...            ...       ...
538159  2016-10-28   391.292
538160  2016-10-28    78.769
538161  2016-10-28   993.760
538162  2016-10-28     0.000
538163  2016-10-28     3.000

[1782 rows x 2 columns]

In [27]:
mask = retail_df['family'].isin(['CLEANING', 'DAIRY'])
retail_df.loc[mask].count()

id             63936
date           63936
store_nbr      63936
family         63936
sales          63936
onpromotion    63936
dtype: int64

In [33]:
mask = mask & retail_df.sales > 0
retail_df.iloc[mask].count()

id             62415
date           62415
store_nbr      62415
family         62415
sales          62415
onpromotion    62415
dtype: int64

In [62]:
oil = pd.read_csv('./assets/oil.csv', parse_dates=['date'])
oil['benchmark'] = 100
oil.head()

        date  dcoilwtico  benchmark
0 2013-01-01         NaN        100
1 2013-01-02       93.14        100
2 2013-01-03       92.97        100
3 2013-01-04       93.12        100
4 2013-01-07       93.20        100

In [43]:
oil.describe()

        dcoilwtico  benchmark
count  1175.000000     1218.0
mean     67.714366      100.0
std      25.630476        0.0
min      26.190000      100.0
25%      46.405000      100.0
50%      53.190000      100.0
75%      95.660000      100.0
max     110.620000      100.0

In [46]:
mask = oil['dcoilwtico'] >= 100
oil.loc[mask]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
407  2014-07-24      102.76        100
408  2014-07-25      105.23        100
409  2014-07-28      105.68        100
410  2014-07-29      104.91        100
411  2014-07-30      104.29        100

[182 rows x 3 columns]

In [47]:
mask = oil.date.str[:4].eq('2013')
oil.loc[mask]

           date  dcoilwtico  benchmark
0    2013-01-01         NaN        100
1    2013-01-02       93.14        100
2    2013-01-03       92.97        100
3    2013-01-04       93.12        100
4    2013-01-07       93.20        100
..          ...         ...        ...
256  2013-12-25         NaN        100
257  2013-12-26       99.18        100
258  2013-12-27       99.94        100
259  2013-12-30       98.90        100
260  2013-12-31       98.17        100

[261 rows x 3 columns]

In [48]:
oil[mask].nunique()

date          261
dcoilwtico    231
benchmark       1
dtype: int64

In [49]:
retail_df.query("family in ['CLEANING', 'DAIRY'] and sales > 0")

              id        date  store_nbr    family   sales  onpromotion
568      1946512  2016-01-01         25  CLEANING   734.0            0
569      1946513  2016-01-01         25     DAIRY  1033.0           11
1789     1947733  2016-01-02          1  CLEANING   526.0            3
1790     1947734  2016-01-02          1     DAIRY   627.0           15
1822     1947766  2016-01-02         10  CLEANING  1216.0            4
...          ...         ...        ...       ...     ...          ...
1054853  3000797  2017-08-15          7     DAIRY  1279.0           25
1054885  3000829  2017-08-15          8  CLEANING  1198.0           13
1054886  3000830  2017-08-15          8     DAIRY  1330.0           24
1054918  3000862  2017-08-15          9  CLEANING  1439.0           25
1054919  3000863  2017-08-15          9     DAIRY   835.0           19

[62415 rows x 6 columns]

In [52]:
avg_sale = retail_df['sales'].mean()
avg_sale

np.float64(457.72248700136424)

In [58]:
retail_df.query("family in ['CLEANING', 'DAIRY'] and sales > @avg_sale").head()

           id        date  store_nbr    family   sales  onpromotion
568   1946512  2016-01-01         25  CLEANING   734.0            0
569   1946513  2016-01-01         25     DAIRY  1033.0           11
1789  1947733  2016-01-02          1  CLEANING   526.0            3
1790  1947734  2016-01-02          1     DAIRY   627.0           15
1822  1947766  2016-01-02         10  CLEANING  1216.0            4

In [63]:
oil.query("dcoilwtico > benchmark or date.dt.year == 2013")

          date  dcoilwtico  benchmark
0   2013-01-01         NaN        100
1   2013-01-02       93.14        100
2   2013-01-03       92.97        100
3   2013-01-04       93.12        100
4   2013-01-07       93.20        100
..         ...         ...        ...
407 2014-07-24      102.76        100
408 2014-07-25      105.23        100
409 2014-07-28      105.68        100
410 2014-07-29      104.91        100
411 2014-07-30      104.29        100

[367 rows x 3 columns]