In [1]:
import numpy as np
import pandas as pd

In [5]:
retail_df = pd.read_csv('./assets/retail.csv')
condition = retail_df['family'].isin(['BEVERAGES', 'DELL', 'DAIRY'])
sample_df = retail_df.loc[condition].sample(5, random_state=2021)
sample_df

             id        date  store_nbr     family   sales  onpromotion
481473  2427417  2016-09-27         19  BEVERAGES  1720.0            8
267737  2213681  2016-05-30         21      DAIRY   548.0            4
191573  2137517  2016-04-17         34      DAIRY   342.0            0
402669  2348613  2016-08-13          8  BEVERAGES  4627.0           39
722444  2668388  2017-02-10          3      DAIRY  2360.0           20

In [6]:
sample_df.sort_index(axis=1)

              date     family       id  onpromotion   sales  store_nbr
481473  2016-09-27  BEVERAGES  2427417            8  1720.0         19
267737  2016-05-30      DAIRY  2213681            4   548.0         21
191573  2016-04-17      DAIRY  2137517            0   342.0         34
402669  2016-08-13  BEVERAGES  2348613           39  4627.0          8
722444  2017-02-10      DAIRY  2668388           20  2360.0          3

In [7]:
sample_df.sort_index(axis=1, ascending=False)

        store_nbr   sales  onpromotion       id     family        date
481473         19  1720.0            8  2427417  BEVERAGES  2016-09-27
267737         21   548.0            4  2213681      DAIRY  2016-05-30
191573         34   342.0            0  2137517      DAIRY  2016-04-17
402669          8  4627.0           39  2348613  BEVERAGES  2016-08-13
722444          3  2360.0           20  2668388      DAIRY  2017-02-10

In [10]:
sample_df.sort_index(axis=1, ascending=True, inplace=True)
sample_df

              date     family       id  onpromotion   sales  store_nbr
481473  2016-09-27  BEVERAGES  2427417            8  1720.0         19
267737  2016-05-30      DAIRY  2213681            4   548.0         21
191573  2016-04-17      DAIRY  2137517            0   342.0         34
402669  2016-08-13  BEVERAGES  2348613           39  4627.0          8
722444  2017-02-10      DAIRY  2668388           20  2360.0          3

In [11]:
sample_df.sort_values('store_nbr')

              date     family       id  onpromotion   sales  store_nbr
722444  2017-02-10      DAIRY  2668388           20  2360.0          3
402669  2016-08-13  BEVERAGES  2348613           39  4627.0          8
481473  2016-09-27  BEVERAGES  2427417            8  1720.0         19
267737  2016-05-30      DAIRY  2213681            4   548.0         21
191573  2016-04-17      DAIRY  2137517            0   342.0         34

In [12]:
sample_df.sort_values('store_nbr', ascending=False)

              date     family       id  onpromotion   sales  store_nbr
191573  2016-04-17      DAIRY  2137517            0   342.0         34
267737  2016-05-30      DAIRY  2213681            4   548.0         21
481473  2016-09-27  BEVERAGES  2427417            8  1720.0         19
402669  2016-08-13  BEVERAGES  2348613           39  4627.0          8
722444  2017-02-10      DAIRY  2668388           20  2360.0          3

In [14]:
sample_df.sort_values(['family', 'sales'], ascending=[True, False])

              date     family       id  onpromotion   sales  store_nbr
402669  2016-08-13  BEVERAGES  2348613           39  4627.0          8
481473  2016-09-27  BEVERAGES  2427417            8  1720.0         19
722444  2017-02-10      DAIRY  2668388           20  2360.0          3
267737  2016-05-30      DAIRY  2213681            4   548.0         21
191573  2016-04-17      DAIRY  2137517            0   342.0         34

In [18]:
oil = pd.read_csv('./assets/oil.csv')
oil['benchmark'] = 100
oil.head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN        100
1  2013-01-02       93.14        100
2  2013-01-03       92.97        100
3  2013-01-04       93.12        100
4  2013-01-07       93.20        100

In [17]:
oil.sort_index(axis=0, ascending=False)

            date  dcoilwtico
1217  2017-08-31       47.26
1216  2017-08-30       45.96
1215  2017-08-29       46.46
1214  2017-08-28       46.40
1213  2017-08-25       47.65
...          ...         ...
4     2013-01-07       93.20
3     2013-01-04       93.12
2     2013-01-03       92.97
1     2013-01-02       93.14
0     2013-01-01         NaN

[1218 rows x 2 columns]

In [19]:
oil.sort_index(ascending=True, axis=1)

      benchmark        date  dcoilwtico
0           100  2013-01-01         NaN
1           100  2013-01-02       93.14
2           100  2013-01-03       92.97
3           100  2013-01-04       93.12
4           100  2013-01-07       93.20
...         ...         ...         ...
1213        100  2017-08-25       47.65
1214        100  2017-08-28       46.40
1215        100  2017-08-29       46.46
1216        100  2017-08-30       45.96
1217        100  2017-08-31       47.26

[1218 rows x 3 columns]

In [24]:
oil['month'] = pd.to_datetime(oil['date']).dt.month
oil.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[us]
 1   dcoilwtico  1175 non-null   float64
 2   benchmark   1218 non-null   int64
 3   month       1218 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(1), int64(1)
memory usage: 33.4 KB

In [25]:
oil.sort_values('dcoilwtico')

           date  dcoilwtico  benchmark  month
812  2016-02-11       26.19        100      2
796  2016-01-20       26.68        100      1
811  2016-02-10       27.54        100      2
810  2016-02-09       27.96        100      2
795  2016-01-19       28.47        100      1
...         ...         ...        ...    ...
1079 2017-02-20         NaN        100      2
1118 2017-04-14         NaN        100      4
1149 2017-05-29         NaN        100      5
1174 2017-07-03         NaN        100      7
1175 2017-07-04         NaN        100      7

[1218 rows x 4 columns]

In [26]:
oil.sort_values('dcoilwtico', ascending=False)

           date  dcoilwtico  benchmark  month
178  2013-09-06      110.62        100      9
171  2013-08-28      110.17        100      8
179  2013-09-09      109.62        100      9
170  2013-08-27      109.11        100      8
182  2013-09-12      108.72        100      9
...         ...         ...        ...    ...
1079 2017-02-20         NaN        100      2
1118 2017-04-14         NaN        100      4
1149 2017-05-29         NaN        100      5
1174 2017-07-03         NaN        100      7
1175 2017-07-04         NaN        100      7

[1218 rows x 4 columns]

In [27]:
oil.sort_values(['month', 'dcoilwtico'], ascending=[True, False])

           date  dcoilwtico  benchmark  month
282  2014-01-30       98.25        100      1
21   2013-01-30       97.98        100      1
22   2013-01-31       97.65        100      1
20   2013-01-29       97.62        100      1
283  2014-01-31       97.55        100      1
...         ...         ...        ...    ...
774  2015-12-21       34.55        100     12
256  2013-12-25         NaN        100     12
517  2014-12-25         NaN        100     12
778  2015-12-25         NaN        100     12
1039 2016-12-26         NaN        100     12

[1218 rows x 4 columns]