In [1]:
import numpy as np
import pandas as pd

In [2]:
product_df = pd.DataFrame(
    {'product': ['DAIRY', 'DAIRY', 'DAIRY', 'VEGETABLES', 'FRUITS'],
     'price': [2.56, 2.56, 4.55, 2.74, 5.44]}
)
product_df

      product  price
0       DAIRY   2.56
1       DAIRY   2.56
2       DAIRY   4.55
3  VEGETABLES   2.74
4      FRUITS   5.44

In [3]:
product_df.columns = ['product_name', 'cost']
product_df

  product_name  cost
0        DAIRY  2.56
1        DAIRY  2.56
2        DAIRY  4.55
3   VEGETABLES  2.74
4       FRUITS  5.44

In [4]:
product_df.columns = [col.upper() for col in product_df.columns]
product_df

  PRODUCT_NAME  COST
0        DAIRY  2.56
1        DAIRY  2.56
2        DAIRY  4.55
3   VEGETABLES  2.74
4       FRUITS  5.44

In [5]:
product_df.rename(columns={'PRODUCT_NAME': 'product_name', 'COST': 'cost'})

  product_name  cost
0        DAIRY  2.56
1        DAIRY  2.56
2        DAIRY  4.55
3   VEGETABLES  2.74
4       FRUITS  5.44

In [6]:
product_df.rename(columns=lambda x: x.upper())

  PRODUCT_NAME  COST
0        DAIRY  2.56
1        DAIRY  2.56
2        DAIRY  4.55
3   VEGETABLES  2.74
4       FRUITS  5.44

In [28]:
product_df = product_df.rename(columns={'PRODUCT_NAME': 'product', 'COST': 'price'})
product_df['product_id'] = range(5)
product_df.reindex(labels=['product_id', 'product', 'price'], axis=1)

   product_id     product  price
0           0       DAIRY   2.56
1           1       DAIRY   2.56
2           2       DAIRY   4.55
3           3  VEGETABLES   2.74
4           4      FRUITS   5.44