In [1]:
import numpy as np
import pandas as pd

In [4]:
retail_df = pd.read_csv('./assets/retail.csv')
retail_df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [22]:
condition = retail_df['family'].isin(['BABY CARE', 'BOOKS']) & retail_df['sales'] > 0
baby_books = retail_df.loc[condition].sample(5, random_state=2018)
baby_books

              id        date  store_nbr     family  sales  onpromotion
653503   2599447  2017-01-02         45      BOOKS    2.0            0
1009042  2954986  2017-07-21         21  BABY CARE    2.0            0
490315   2436259  2016-10-02         17  BABY CARE    1.0            0
665977   2611921  2017-01-09         45      BOOKS    7.0            0
814573   2760517  2017-04-03         15  BABY CARE    2.0            0

In [23]:
baby_books['tax_amount'] = baby_books['sales'] * 0.05
baby_books['total'] = baby_books['sales'] + baby_books['tax_amount']
baby_books

,id,date,store_nbr,family,sales,onpromotion,tax_amount,total
653503,2599447,2017-01-02,45,BOOKS,2.0,0,0.10,2.10
1009042,2954986,2017-07-21,21,BABY CARE,2.0,0,0.10,2.10
490315,2436259,2016-10-02,17,BABY CARE,1.0,0,0.05,1.05
665977,2611921,2017-01-09,45,BOOKS,7.0,0,0.35,7.35
814573,2760517,2017-04-03,15,BABY CARE,2.0,0,0.10,2.10

In [27]:
baby_books['taxable_category'] = baby_books['family'] != 'BABY CARE'
baby_books.drop(['tax_amount', 'total'], axis=1, inplace=True)
baby_books

,id,date,store_nbr,family,sales,onpromotion,taxable_category
653503,2599447,2017-01-02,45,BOOKS,2.0,0,True
1009042,2954986,2017-07-21,21,BABY CARE,2.0,0,False
490315,2436259,2016-10-02,17,BABY CARE,1.0,0,False
665977,2611921,2017-01-09,45,BOOKS,7.0,0,True
814573,2760517,2017-04-03,15,BABY CARE,2.0,0,False

In [31]:
baby_books.drop('taxable_category', axis=1, inplace=True)
baby_books['tax_amount'] = (
    baby_books['sales'] * 0.05 * (baby_books['family'] != 'BABY CARE')
)
baby_books

,id,date,store_nbr,family,sales,onpromotion,tax_amount
653503,2599447,2017-01-02,45,BOOKS,2.0,0,0.10
1009042,2954986,2017-07-21,21,BABY CARE,2.0,0,0.00
490315,2436259,2016-10-02,17,BABY CARE,1.0,0,0.00
665977,2611921,2017-01-09,45,BOOKS,7.0,0,0.35
814573,2760517,2017-04-03,15,BABY CARE,2.0,0,0.00

In [32]:
oil = pd.read_csv('./assets/oil.csv')
oil['benchmark'] = 90
oil.head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN         90
1  2013-01-02       93.14         90
2  2013-01-03       92.97         90
3  2013-01-04       93.12         90
4  2013-01-07       93.20         90

In [35]:
oil['benchmark_ratio'] = oil['dcoilwtico'] / oil['benchmark'] * 100
oil

            date  dcoilwtico  benchmark  benchmark_ratio
0     2013-01-01         NaN         90              NaN
1     2013-01-02       93.14         90       103.488889
2     2013-01-03       92.97         90       103.300000
3     2013-01-04       93.12         90       103.466667
4     2013-01-07       93.20         90       103.555556
...          ...         ...        ...              ...
1213  2017-08-25       47.65         90        52.944444
1214  2017-08-28       46.40         90        51.555556
1215  2017-08-29       46.46         90        51.622222
1216  2017-08-30       45.96         90        51.066667
1217  2017-08-31       47.26         90        52.511111

[1218 rows x 4 columns]

In [39]:
oil['buy'] = (oil.loc[:, 'benchmark_ratio'] < 80) * 1000000 / oil.loc[:, 'dcoilwtico']
oil

            date  dcoilwtico  benchmark  benchmark_ratio           buy
0     2013-01-01         NaN         90              NaN           NaN
1     2013-01-02       93.14         90       103.488889      0.000000
2     2013-01-03       92.97         90       103.300000      0.000000
3     2013-01-04       93.12         90       103.466667      0.000000
4     2013-01-07       93.20         90       103.555556      0.000000
...          ...         ...        ...              ...           ...
1213  2017-08-25       47.65         90        52.944444  20986.358867
1214  2017-08-28       46.40         90        51.555556  21551.724138
1215  2017-08-29       46.46         90        51.622222  21523.891520
1216  2017-08-30       45.96         90        51.066667  21758.050479
1217  2017-08-31       47.26         90        52.511111  21159.542954

[1218 rows x 5 columns]