In [1]:
import pandas as pd
import numpy as np

# Assignment 1: DataFrame Basics

Hi there!

Can you read in the transactions dataset and report on:

* The number of rows and columns
* The names of the columns
* The datatypes of each column

In [2]:
# A common practice is to create a path variable to pass to read_csv
path = "./assets/transactions.csv"
transactions = pd.read_csv(path)
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [3]:
transactions.shape

(83488, 3)

In [4]:
transactions.columns

Index(['date', 'store_nbr', 'transactions'], dtype='str')

In [5]:
transactions.dtypes

date              str
store_nbr       int64
transactions    int64
dtype: object

# Assignment 2: Exploring DataFrames

Hello!

* Can you quickly inspect the first 5 rows of the transactions data? 

* Then, dive a bit more deeply into the data and check if there are any missing values.
* What about the number of unique dates? I want to make sure we didn’t leave any out.
* Finally, can you report the mean, median, min and max of “transactions”?  I want to check for any anomalies in our data.

In [6]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [7]:
transactions.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [8]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  str
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), str(1)
memory usage: 1.9 MB

In [9]:
transactions.describe(include='all')

              date     store_nbr  transactions
count        83488  83488.000000  83488.000000
unique        1682           NaN           NaN
top     2017-04-20           NaN           NaN
freq            54           NaN           NaN
mean           NaN     26.939237   1694.602158
std            NaN     15.608204    963.286644
min            NaN      1.000000      5.000000
25%            NaN     13.000000   1046.000000
50%            NaN     27.000000   1393.000000
75%            NaN     40.000000   2079.000000
max            NaN     54.000000   8359.000000

# Exercise 3 - Accessing DataFrames

Hi, starting to dive deeper into this data.

I noticed that the first row is the only one from 2013-01-01.

* Can you get me a copy of the DataFrame that excludes that row, and only includes “store_nbr” and “transactions”?
* Also, can you report the number of unique store numbers?
* Finally, return the total number of transactions in millions

In [10]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [14]:
transactions.loc[1:, ['store_nbr', 'transactions']]

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [16]:
transactions.loc[:, 'store_nbr'].nunique()

54

In [20]:
transactions['transactions'].sum() / 1000000

np.float64(141.478945)

# Assignment 4: Dropping Data and Duplicates

Hi there!

Can you:

1. Drop the first row of data? We want it permanently removed. 
2. Drop the date column but not in place
3. Return a dataframe that only includes the last row for each of the stores.

Thanks!

In [12]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

# Assignment 5: Missing Data

Hello, 

Can you tell if any dates or prices are missing in the oil dataset?

Then compare the mean of the oil series when filling in with mean vs. filling in with 0.

Thanks!

In [13]:
oil = pd.read_csv("../retail/oil.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../retail/oil.csv'

# Assignment 6: Filtering DataFrames

I need some quick research on store 25:

* First, calculate the percentage of times ALL stores had more than 2000 transactions
* Then, calculate the percentage of times store 25 had more than 2000 transactions, and calculate the sum of transactions on these days
* Finally, sum the transactions for stores 25 and 31, that occurred in May or June, and had less than 2000 transactions

In [ ]:
transactions.head()

In [ ]:
transactions.query("date.str[6] == '1'")

NameError: name 'transactions' is not defined

# Assignment 7: Sorting DataFrames

Hi there,
* Can you get me a dataset that includes the 5 days with the highest transactions counts? Any similarities between them?
* Then, can you get me a dataset sorted by date from earliest to most recent, but with the highest transactions first and the lowest transactions last for each day?
* Finally, sort the columns in reverse alphabetical order. 

Thanks!

In [ ]:
transactions.head()

# Assignment 8: Modifying Columns

Just some quick work, but can you send me the transaction data with the columns renamed?

* Rename `transactions` to `transaction_count` and `store_nbr` to `store_number`.
* Reorder the columns so date is first, then store number, then transaction count.

Thanks!

In [ ]:
transactions.head()

# Assignment 9: Column Creation

Just some quick work, but can you send me the transaction data with the columns renamed?

* Create a `pct_to_target` column that divides transactions by 2500.
* Then, create a `met_target` column that returns True if `pct_to_target` is greater than or equal to 1.
* Next, create a `bonus_payable` column that equals 100 if `met_target` is True, and 0 if not. Then sum the bonus payable column.
* Finally, create columns for month and day of week as integers. There is some helper code for these dateparts below.



Thanks!

In [ ]:
transactions.head()

# Assignment 10: np.select

Hi there! I need a few columns created.

1. Create a ‘seasonal_bonus’ column that applies to these dates: 
    * All days in December (month = 12)
    * Sundays (day_of_week = 6) in May (month = 5)
    * Mondays (day_of_week = 0) in July (month = 7)
2. Call the December bonus ‘Holiday Bonus’, the May bonus ‘Corporate Month’, and the July bonus ‘Summer Special’. If no bonus applies, the column should display ‘None’. 
3. Finally, calculate the total bonus owed at $100 per day.

Thanks!

In [ ]:
transactions.head()

# Assignment 11: Assign 

* Drop the columns that have been created so far (keep only date, store_number, and transaction count), and recreate them using the assign method.
* Then sum the seasonal bonus owed once again to make sure the numbers are correct.

In [ ]:
# Drop columns we created in prior exercises

In [ ]:
# Create same columns with assign

# Assignment 12: Memory Optimization

Reduce the memory usage of the transactions DataFrame to below 5MB.

In [ ]:
transactions.head()

In [ ]:
transactions.info(memory_usage="deep")