In [1]:
import pandas as pd
import numpy as np

# Assignment 1: DataFrame Basics

Hi there!

Can you read in the transactions dataset and report on:

* The number of rows and columns
* The names of the columns
* The datatypes of each column

In [2]:
# A common practice is to create a path variable to pass to read_csv
path = "./assets/transactions.csv"
transactions = pd.read_csv(path)
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [3]:
transactions.shape

(83488, 3)

In [4]:
transactions.columns

Index(['date', 'store_nbr', 'transactions'], dtype='str')

In [5]:
transactions.dtypes

date              str
store_nbr       int64
transactions    int64
dtype: object

# Assignment 2: Exploring DataFrames

Hello!

* Can you quickly inspect the first 5 rows of the transactions data? 

* Then, dive a bit more deeply into the data and check if there are any missing values.
* What about the number of unique dates? I want to make sure we didn’t leave any out.
* Finally, can you report the mean, median, min and max of “transactions”?  I want to check for any anomalies in our data.

In [6]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [7]:
transactions.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [8]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  str
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), str(1)
memory usage: 2.7 MB

In [9]:
transactions.describe(include='all')

              date     store_nbr  transactions
count        83488  83488.000000  83488.000000
unique        1682           NaN           NaN
top     2017-04-20           NaN           NaN
freq            54           NaN           NaN
mean           NaN     26.939237   1694.602158
std            NaN     15.608204    963.286644
min            NaN      1.000000      5.000000
25%            NaN     13.000000   1046.000000
50%            NaN     27.000000   1393.000000
75%            NaN     40.000000   2079.000000
max            NaN     54.000000   8359.000000

# Exercise 3 - Accessing DataFrames

Hi, starting to dive deeper into this data.

I noticed that the first row is the only one from 2013-01-01.

* Can you get me a copy of the DataFrame that excludes that row, and only includes “store_nbr” and “transactions”?
* Also, can you report the number of unique store numbers?
* Finally, return the total number of transactions in millions

In [10]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [11]:
transactions.loc[1:, ['store_nbr', 'transactions']]

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [12]:
transactions.loc[:, 'store_nbr'].nunique()

54

In [13]:
transactions['transactions'].sum() / 1000000

np.float64(141.478945)

# Assignment 4: Dropping Data and Duplicates

Hi there!

Can you:

1. Drop the first row of data? We want it permanently removed. 
2. Drop the date column but not in place
3. Return a dataframe that only includes the last row for each of the stores.

Thanks!

In [14]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [15]:
transactions.drop(0, axis=0, inplace=True)
transactions.head()

         date  store_nbr  transactions
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [16]:
transactions.drop('date', axis=1)

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [17]:
transactions.drop_duplicates(subset='store_nbr', keep='last', ignore_index=True)

          date  store_nbr  transactions
0   2017-08-15          1          1693
1   2017-08-15          2          1737
2   2017-08-15          3          2956
3   2017-08-15          4          1283
4   2017-08-15          5          1310
5   2017-08-15          6          1589
6   2017-08-15          7          1780
7   2017-08-15          8          2621
8   2017-08-15          9          2155
9   2017-08-15         10          1010
10  2017-08-15         11          2360
11  2017-08-15         12          1096
12  2017-08-15         13           842
13  2017-08-15         14          1241
14  2017-08-15         15          1320
15  2017-08-15         16           742
16  2017-08-15         17          1504
17  2017-08-15         18          1343
18  2017-08-15         19          1158
19  2017-08-15         20          1516
20  2017-08-15         21          1059
21  2017-08-15         22           766
22  2017-08-15         23           946
23  2017-08-15         24          2138
24  2017-08-15         25           849
25  2017-08-15         26           534
26  2017-08-15         27          1543
27  2017-08-15         28          1343
28  2017-08-15         29          1302
29  2017-08-15         30           825
30  2017-08-15         31          1360
31  2017-08-15         32           615
32  2017-08-15         33           919
33  2017-08-15         34          2007
34  2017-08-15         35           612
35  2017-08-15         36          1192
36  2017-08-15         37          1373
37  2017-08-15         38          1445
38  2017-08-15         39          1425
39  2017-08-15         40          1392
40  2017-08-15         41          1003
41  2017-08-15         42           995
42  2017-08-15         43          1482
43  2017-08-15         44          3815
44  2017-08-15         45          3685
45  2017-08-15         46          3197
46  2017-08-15         47          3581
47  2017-08-15         48          2722
48  2017-08-15         49          2814
49  2017-08-15         50          2804
50  2017-08-15         51          1573
51  2017-08-15         52          2255
52  2017-08-15         53           932
53  2017-08-15         54           802

# Assignment 5: Missing Data

Hello, 

Can you tell if any dates or prices are missing in the oil dataset?

Then compare the mean of the oil series when filling in with mean vs. filling in with 0.

Thanks!

In [18]:
oil = pd.read_csv("./assets/oil.csv")
oil.columns = ['date', 'price']
oil.head()

         date  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [19]:
oil.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1218 non-null   str
 1   price   1175 non-null   float64
dtypes: float64(1), str(1)
memory usage: 31.1 KB

In [20]:
oil.isna().sum()

date      0
price    43
dtype: int64

In [21]:
oil['price'].mean()

np.float64(67.71436595744682)

In [22]:
oil_filled_with_mean = oil.fillna({'price': oil['price'].mean()})
oil_filled_with_mean.loc[:,'price'].mean()

np.float64(67.71436595744682)

In [23]:
oil_filled_with_zero = oil.fillna({'price': 0})
oil_filled_with_zero['price'].mean()

np.float64(65.32379310344828)

# Assignment 6: Filtering DataFrames

I need some quick research on store 25:

* First, calculate the percentage of times ALL stores had more than 2000 transactions
* Then, calculate the percentage of times store 25 had more than 2000 transactions, and calculate the sum of transactions on these days
* Finally, sum the transactions for stores 25 and 31, that occurred in May or June, and had less than 2000 transactions

In [24]:
transactions.head()

         date  store_nbr  transactions
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [25]:
(transactions['transactions'] > 2000).mean()

np.float64(0.266808006036868)

In [26]:
(transactions.query("store_nbr == 25")['transactions'] > 2000).mean()

np.float64(0.03469640644361834)

In [27]:
transactions.query('store_nbr == 25 and transactions > 2000')['transactions'].sum()

np.int64(144903)

In [28]:
transactions.query("store_nbr in [25, 31] and date.str[6] in ['5', '6'] and transactions < 2000").transactions.sum()

np.int64(644910)

# Assignment 7: Sorting DataFrames

Hi there,
* Can you get me a dataset that includes the 5 days with the highest transactions counts? Any similarities between them?
* Then, can you get me a dataset sorted by date from earliest to most recent, but with the highest transactions first and the lowest transactions last for each day?
* Finally, sort the columns in reverse alphabetical order. 

Thanks!

In [29]:
transactions.head()

         date  store_nbr  transactions
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [30]:
transactions.sort_values('transactions', ascending=False).head(5)

             date  store_nbr  transactions
52011  2015-12-23         44          8359
71010  2016-12-23         44          8307
16570  2013-12-23         44          8256
33700  2014-12-23         44          8120
16572  2013-12-23         46          8001

In [31]:
transactions.sort_values(['date', 'transactions'], ascending=[True, False])

             date  store_nbr  transactions
40     2013-01-02         46          4886
38     2013-01-02         44          4821
39     2013-01-02         45          4208
41     2013-01-02         47          4161
11     2013-01-02         11          3547
...           ...        ...           ...
83455  2017-08-15         22           766
83449  2017-08-15         16           742
83465  2017-08-15         32           615
83468  2017-08-15         35           612
83459  2017-08-15         26           534

[83487 rows x 3 columns]

In [32]:
transactions.sort_index(axis=1, ascending=False)

       transactions  store_nbr        date
1              2111          1  2013-01-02
2              2358          2  2013-01-02
3              3487          3  2013-01-02
4              1922          4  2013-01-02
5              1903          5  2013-01-02
...             ...        ...         ...
83483          2804         50  2017-08-15
83484          1573         51  2017-08-15
83485          2255         52  2017-08-15
83486           932         53  2017-08-15
83487           802         54  2017-08-15

[83487 rows x 3 columns]

# Assignment 8: Modifying Columns

Just some quick work, but can you send me the transaction data with the columns renamed?

* Rename `transactions` to `transaction_count` and `store_nbr` to `store_number`.
* Reorder the columns so date is first, then store number, then transaction count.

Thanks!

In [33]:
transactions.head()

         date  store_nbr  transactions
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [35]:
transactions.rename(columns={'transactions': 'transaction_count', 'store_nbr': 'store_number'}).head()

         date  store_number  transaction_count
1  2013-01-02             1               2111
2  2013-01-02             2               2358
3  2013-01-02             3               3487
4  2013-01-02             4               1922
5  2013-01-02             5               1903

# Assignment 9: Column Creation

Just some quick work, but can you send me the transaction data with the columns renamed?

* Create a `pct_to_target` column that divides transactions by 2500.
* Then, create a `met_target` column that returns True if `pct_to_target` is greater than or equal to 1.
* Next, create a `bonus_payable` column that equals 100 if `met_target` is True, and 0 if not. Then sum the bonus payable column.
* Finally, create columns for month and day of week as integers. There is some helper code for these dateparts below.



Thanks!

In [45]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

# Assignment 10: np.select

Hi there! I need a few columns created.

1. Create a ‘seasonal_bonus’ column that applies to these dates: 
    * All days in December (month = 12)
    * Sundays (day_of_week = 6) in May (month = 5)
    * Mondays (day_of_week = 0) in July (month = 7)
2. Call the December bonus ‘Holiday Bonus’, the May bonus ‘Corporate Month’, and the July bonus ‘Summer Special’. If no bonus applies, the column should display ‘None’. 
3. Finally, calculate the total bonus owed at $100 per day.

Thanks!

In [46]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

# Assignment 11: Assign 

* Drop the columns that have been created so far (keep only date, store_number, and transaction count), and recreate them using the assign method.
* Then sum the seasonal bonus owed once again to make sure the numbers are correct.

In [47]:
# Drop columns we created in prior exercises

In [48]:
# Create same columns with assign

# Assignment 12: Memory Optimization

Reduce the memory usage of the transactions DataFrame to below 5MB.

In [49]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [50]:
transactions.info(memory_usage="deep")

<class 'pandas.DataFrame'>
Index: 83487 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83487 non-null  str
 1   store_nbr     83487 non-null  int64
 2   transactions  83487 non-null  int64
dtypes: int64(2), str(1)
memory usage: 3.4 MB