In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv("./assets/retail.csv")
retail.groupby('family')

In [3]:
retail.groupby('family')[['sales']].sum().head()

                  sales
family
AUTOMOTIVE     226139.0
BABY CARE        7903.0
BEAUTY         166189.0
BEVERAGES   105700279.0
BOOKS            6438.0

In [4]:
premier_league = pd.read_csv('./assets/premier_league_games.csv')
premier_league.head()

,id,league_name,season,home_team,away_team,home_goals,away_goals
0,1,Premier League,1993/1994,Arsenal,Coventry,0,3
1,2,Premier League,1993/1994,Aston Villa,QPR,4,1
2,3,Premier League,1993/1994,Chelsea,Blackburn,1,2
3,4,Premier League,1993/1994,Liverpool,Sheffield Weds,2,0
4,5,Premier League,1993/1994,Man City,Leeds,1,1

In [5]:
premier_league.groupby('home_team')[['home_goals']].mean().sort_values('home_goals', ascending=False).head()

            home_goals
home_team
Man City      2.100746
Arsenal       2.069731
Man United    2.066561
Liverpool     2.038035
Chelsea       1.928685

In [6]:
premier_league.groupby('away_team')[['away_goals']].mean().sort_values('away_goals', ascending=False).head()

            away_goals
away_team
Man United    1.651347
Arsenal       1.568938
Liverpool     1.557845
Man City      1.520522
Chelsea       1.492868

In [7]:
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [8]:
# multi index
retail.groupby(['family', 'store_nbr'])[['sales']].sum()

                             sales
family     store_nbr
AUTOMOTIVE 1           2524.000000
           2           3918.000000
           3           6790.000000
           4           2565.000000
           5           3667.000000
...                            ...
SEAFOOD    50         12773.966999
           51         34250.948976
           52          1219.475999
           53          3745.180001
           54          1082.000000

[1782 rows x 1 columns]

In [9]:
retail.groupby(['family', 'store_nbr'], as_index=False)[['sales']].sum()

          family  store_nbr         sales
0     AUTOMOTIVE          1   2524.000000
1     AUTOMOTIVE          2   3918.000000
2     AUTOMOTIVE          3   6790.000000
3     AUTOMOTIVE          4   2565.000000
4     AUTOMOTIVE          5   3667.000000
...          ...        ...           ...
1777     SEAFOOD         50  12773.966999
1778     SEAFOOD         51  34250.948976
1779     SEAFOOD         52   1219.475999
1780     SEAFOOD         53   3745.180001
1781     SEAFOOD         54   1082.000000

[1782 rows x 3 columns]

In [10]:
(premier_league.groupby(['home_team', 'season'], as_index=False)[['home_goals']].sum()
    .sort_values(['home_team', 'season'], ascending=[True, False]))

    home_team     season  home_goals
32    Arsenal  2025/2026          41
31    Arsenal  2024/2025          35
30    Arsenal  2023/2024          48
29    Arsenal  2022/2023          53
28    Arsenal  2021/2022          35
..        ...        ...         ...
656    Wolves  2018/2019          28
655    Wolves  2011/2012          19
654    Wolves  2010/2011          30
653    Wolves  2009/2010          13
652    Wolves  2003/2004          23

[664 rows x 3 columns]

In [11]:
sales_sums = retail.groupby(['family', 'store_nbr'])[['sales']].sum()
sales_sums

                             sales
family     store_nbr
AUTOMOTIVE 1           2524.000000
           2           3918.000000
           3           6790.000000
           4           2565.000000
           5           3667.000000
...                            ...
SEAFOOD    50         12773.966999
           51         34250.948976
           52          1219.475999
           53          3745.180001
           54          1082.000000

[1782 rows x 1 columns]

In [12]:
sales_sums.index

MultiIndex([('AUTOMOTIVE',  1),
            ('AUTOMOTIVE',  2),
            ('AUTOMOTIVE',  3),
            ('AUTOMOTIVE',  4),
            ('AUTOMOTIVE',  5),
            ('AUTOMOTIVE',  6),
            ('AUTOMOTIVE',  7),
            ('AUTOMOTIVE',  8),
            ('AUTOMOTIVE',  9),
            ('AUTOMOTIVE', 10),
            ...
            (   'SEAFOOD', 45),
            (   'SEAFOOD', 46),
            (   'SEAFOOD', 47),
            (   'SEAFOOD', 48),
            (   'SEAFOOD', 49),
            (   'SEAFOOD', 50),
            (   'SEAFOOD', 51),
            (   'SEAFOOD', 52),
            (   'SEAFOOD', 53),
            (   'SEAFOOD', 54)],
           names=['family', 'store_nbr'], length=1782)

In [13]:
sales_sums.loc['AUTOMOTIVE'].head()

            sales
store_nbr
1          2524.0
2          3918.0
3          6790.0
4          2565.0
5          3667.0

In [14]:
sales_sums.loc['AUTOMOTIVE':'BEAUTY']

                       sales
family     store_nbr
AUTOMOTIVE 1          2524.0
           2          3918.0
           3          6790.0
           4          2565.0
           5          3667.0
...                      ...
BEAUTY     50         6353.0
           51         3566.0
           52          972.0
           53         3812.0
           54          405.0

[162 rows x 1 columns]

In [15]:
sales_sums.loc[('AUTOMOTIVE', 12), :]

sales    3507.0
Name: (AUTOMOTIVE, 12), dtype: float64

In [16]:
sales_sums.loc[('AUTOMOTIVE', 11):('BEAUTY', 11), :]

                       sales
family     store_nbr
AUTOMOTIVE 11         4387.0
           12         3507.0
           13         3499.0
           14         2858.0
           15         1874.0
...                      ...
BEAUTY     7          2622.0
           8          5942.0
           9          4462.0
           10          933.0
           11         4175.0

[109 rows x 1 columns]

In [17]:
premier_league_agg = premier_league.groupby(['season', 'home_team'])[['home_goals']].sum()
premier_league_agg

                         home_goals
season    home_team
1993/1994 Arsenal                25
          Aston Villa            23
          Blackburn              31
          Chelsea                31
          Coventry               23
...                             ...
2025/2026 Nott'm Forest          20
          Sunderland             25
          Tottenham              22
          West Ham               27
          Wolves                 19

[664 rows x 1 columns]

In [18]:
premier_league_agg.loc[('2001/2002', 'Arsenal'):('2001/2002', 'Liverpool')]

                       home_goals
season    home_team
2001/2002 Arsenal              42
          Aston Villa          22
          Blackburn            33
          Bolton               20
          Charlton             23
          Chelsea              43
          Derby                20
          Everton              26
          Fulham               21
          Ipswich              20
          Leeds                31
          Leicester            15
          Liverpool            33

In [19]:
premier_league_agg = premier_league.groupby(['season', 'home_team']).agg({'home_goals': ['sum', 'mean']})
premier_league_agg.head()

                      home_goals
                             sum      mean
season    home_team
1993/1994 Arsenal             25  1.190476
          Aston Villa         23  1.095238
          Blackburn           31  1.476190
          Chelsea             31  1.476190
          Coventry            23  1.095238

In [20]:
premier_league_agg.iloc[0, 1]

np.float64(1.1904761904761905)

In [21]:
premier_league_agg.iloc[0, :]

home_goals  sum     25.000000
            mean     1.190476
Name: (1993/1994, Arsenal), dtype: float64

In [22]:
premier_league_agg.loc['2001/2002', ('home_goals',)]

               sum      mean
home_team
Arsenal         42  2.210526
Aston Villa     22  1.157895
Blackburn       33  1.736842
Bolton          20  1.052632
Charlton        23  1.210526
Chelsea         43  2.263158
Derby           20  1.052632
Everton         26  1.368421
Fulham          21  1.105263
Ipswich         20  1.052632
Leeds           31  1.631579
Leicester       15  0.789474
Liverpool       33  1.736842
Man United      40  2.105263
Middlesbrough   23  1.210526
Newcastle       40  2.105263
Southampton     23  1.210526
Sunderland      18  0.947368
Tottenham       32  1.684211
West Ham        32  1.684211

In [23]:
premier_league_agg.loc['2001/2002', ('home_goals', 'sum')]

home_team
Arsenal          42
Aston Villa      22
Blackburn        33
Bolton           20
Charlton         23
Chelsea          43
Derby            20
Everton          26
Fulham           21
Ipswich          20
Leeds            31
Leicester        15
Liverpool        33
Man United       40
Middlesbrough    23
Newcastle        40
Southampton      23
Sunderland       18
Tottenham        32
West Ham         32
Name: (home_goals, sum), dtype: int64

In [24]:
premier_league_agg.head()

                      home_goals
                             sum      mean
season    home_team
1993/1994 Arsenal             25  1.190476
          Aston Villa         23  1.095238
          Blackburn           31  1.476190
          Chelsea             31  1.476190
          Coventry            23  1.095238

In [25]:
premier_league_agg.droplevel(0, axis=1)

                         sum      mean
season    home_team
1993/1994 Arsenal         25  1.190476
          Aston Villa     23  1.095238
          Blackburn       31  1.476190
          Chelsea         31  1.476190
          Coventry        23  1.095238
...                      ...       ...
2025/2026 Nott'm Forest   20  1.052632
          Sunderland      25  1.315789
          Tottenham       22  1.157895
          West Ham        27  1.421053
          Wolves          19  1.000000

[664 rows x 2 columns]

In [26]:
premier_league_agg.droplevel(0, axis=1).loc[:, 'sum']

season     home_team
1993/1994  Arsenal          25
           Aston Villa      23
           Blackburn        31
           Chelsea          31
           Coventry         23
                            ..
2025/2026  Nott'm Forest    20
           Sunderland       25
           Tottenham        22
           West Ham         27
           Wolves           19
Name: sum, Length: 664, dtype: int64

In [27]:
premier_league_agg = premier_league_agg.droplevel(0, axis=1)

In [28]:
premier_league_agg.loc[(slice(None), 'Arsenal'), :]

                     sum      mean
season    home_team
1993/1994 Arsenal     25  1.190476
1994/1995 Arsenal     27  1.285714
1995/1996 Arsenal     30  1.578947
1996/1997 Arsenal     36  1.894737
1997/1998 Arsenal     43  2.263158
1998/1999 Arsenal     34  1.789474
1999/2000 Arsenal     42  2.210526
2000/2001 Arsenal     45  2.368421
2001/2002 Arsenal     42  2.210526
2002/2003 Arsenal     47  2.473684
2003/2004 Arsenal     40  2.105263
2004/2005 Arsenal     54  2.842105
2005/2006 Arsenal     48  2.526316
2006/2007 Arsenal     43  2.263158
2007/2008 Arsenal     37  1.947368
2008/2009 Arsenal     31  1.631579
2009/2010 Arsenal     48  2.526316
2010/2011 Arsenal     33  1.736842
2011/2012 Arsenal     39  2.052632
2012/2013 Arsenal     47  2.473684
2013/2014 Arsenal     36  1.894737
2014/2015 Arsenal     41  2.157895
2015/2016 Arsenal     31  1.631579
2016/2017 Arsenal     39  2.052632
2017/2018 Arsenal     54  2.842105
2018/2019 Arsenal     42  2.210526
2019/2020 Arsenal     36  1.894737
2020/2021 Arsenal     24  1.263158
2021/2022 Arsenal     35  1.842105
2022/2023 Arsenal     53  2.789474
2023/2024 Arsenal     48  2.526316
2024/2025 Arsenal     35  1.842105
2025/2026 Arsenal     41  2.157895

In [29]:
premier_league_agg.swaplevel().loc['Arsenal']

           sum      mean
season
1993/1994   25  1.190476
1994/1995   27  1.285714
1995/1996   30  1.578947
1996/1997   36  1.894737
1997/1998   43  2.263158
1998/1999   34  1.789474
1999/2000   42  2.210526
2000/2001   45  2.368421
2001/2002   42  2.210526
2002/2003   47  2.473684
2003/2004   40  2.105263
2004/2005   54  2.842105
2005/2006   48  2.526316
2006/2007   43  2.263158
2007/2008   37  1.947368
2008/2009   31  1.631579
2009/2010   48  2.526316
2010/2011   33  1.736842
2011/2012   39  2.052632
2012/2013   47  2.473684
2013/2014   36  1.894737
2014/2015   41  2.157895
2015/2016   31  1.631579
2016/2017   39  2.052632
2017/2018   54  2.842105
2018/2019   42  2.210526
2019/2020   36  1.894737
2020/2021   24  1.263158
2021/2022   35  1.842105
2022/2023   53  2.789474
2023/2024   48  2.526316
2024/2025   35  1.842105
2025/2026   41  2.157895

In [30]:
premier_league_agg.reset_index(inplace=True)

In [33]:
mask = premier_league_agg['home_team'] == 'Arsenal'
premier_league_agg.loc[mask]

        season home_team  sum      mean
0    1993/1994   Arsenal   25  1.190476
22   1994/1995   Arsenal   27  1.285714
44   1995/1996   Arsenal   30  1.578947
64   1996/1997   Arsenal   36  1.894737
84   1997/1998   Arsenal   43  2.263158
104  1998/1999   Arsenal   34  1.789474
124  1999/2000   Arsenal   42  2.210526
144  2000/2001   Arsenal   45  2.368421
164  2001/2002   Arsenal   42  2.210526
184  2002/2003   Arsenal   47  2.473684
204  2003/2004   Arsenal   40  2.105263
224  2004/2005   Arsenal   54  2.842105
244  2005/2006   Arsenal   48  2.526316
264  2006/2007   Arsenal   43  2.263158
284  2007/2008   Arsenal   37  1.947368
304  2008/2009   Arsenal   31  1.631579
324  2009/2010   Arsenal   48  2.526316
344  2010/2011   Arsenal   33  1.736842
364  2011/2012   Arsenal   39  2.052632
384  2012/2013   Arsenal   47  2.473684
404  2013/2014   Arsenal   36  1.894737
424  2014/2015   Arsenal   41  2.157895
444  2015/2016   Arsenal   31  1.631579
464  2016/2017   Arsenal   39  2.052632
484  2017/2018   Arsenal   54  2.842105
504  2018/2019   Arsenal   42  2.210526
524  2019/2020   Arsenal   36  1.894737
544  2020/2021   Arsenal   24  1.263158
564  2021/2022   Arsenal   35  1.842105
584  2022/2023   Arsenal   53  2.789474
604  2023/2024   Arsenal   48  2.526316
624  2024/2025   Arsenal   35  1.842105
644  2025/2026   Arsenal   41  2.157895