In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv('./assets/retail.csv')
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [3]:
retail.groupby(['store_nbr', 'family'])['sales'].sum().round()

store_nbr  family
1          AUTOMOTIVE                       2524.0
           BABY CARE                           0.0
           BEAUTY                           1776.0
           BEVERAGES                     1238601.0
           BOOKS                             211.0
                                           ...
54         POULTRY                         35537.0
           PREPARED FOODS                  42792.0
           PRODUCE                        378612.0
           SCHOOL AND OFFICE SUPPLIES        997.0
           SEAFOOD                          1082.0
Name: sales, Length: 1782, dtype: float64

In [4]:
cols = ['store_nbr', 'family', 'sales', 'onpromotion']
retail.loc[:,cols].groupby(['store_nbr', 'family']).agg('sum')

                                             sales  onpromotion
store_nbr family
1         AUTOMOTIVE                  2.524000e+03           14
          BABY CARE                   0.000000e+00            0
          BEAUTY                      1.776000e+03          190
          BEVERAGES                   1.238601e+06        13793
          BOOKS                       2.110000e+02            0
...                                            ...          ...
54        POULTRY                     3.553737e+04          909
          PREPARED FOODS              4.279200e+04          577
          PRODUCE                     3.786125e+05         6734
          SCHOOL AND OFFICE SUPPLIES  9.970000e+02          277
          SEAFOOD                     1.082000e+03          125

[1782 rows x 2 columns]

In [6]:
retail.loc[:, cols].groupby(['store_nbr', 'family']).agg(['sum', 'mean'])

                                             sales              onpromotion  \
                                               sum         mean         sum
store_nbr family
1         AUTOMOTIVE                  2.524000e+03     4.263514          14
          BABY CARE                   0.000000e+00     0.000000           0
          BEAUTY                      1.776000e+03     3.000000         190
          BEVERAGES                   1.238601e+06  2092.231419       13793
          BOOKS                       2.110000e+02     0.356419           0
...                                            ...          ...         ...
54        POULTRY                     3.553737e+04    60.029334         909
          PREPARED FOODS              4.279200e+04    72.283784         577
          PRODUCE                     3.786125e+05   639.548107        6734
          SCHOOL AND OFFICE SUPPLIES  9.970000e+02     1.684122         277
          SEAFOOD                     1.082000e+03     1.827703         125


                                           mean
store_nbr family
1         AUTOMOTIVE                   0.023649
          BABY CARE                    0.000000
          BEAUTY                       0.320946
          BEVERAGES                   23.298986
          BOOKS                        0.000000
...                                         ...
54        POULTRY                      1.535473
          PREPARED FOODS               0.974662
          PRODUCE                     11.375000
          SCHOOL AND OFFICE SUPPLIES   0.467905
          SEAFOOD                      0.211149

[1782 rows x 4 columns]

In [8]:
(retail.groupby(['store_nbr', 'family'])
     .agg({'sales': ['sum', 'mean'],
           'onpromotion': ['min', 'max']})
)

                                             sales              onpromotion  \
                                               sum         mean         min
store_nbr family
1         AUTOMOTIVE                  2.524000e+03     4.263514           0
          BABY CARE                   0.000000e+00     0.000000           0
          BEAUTY                      1.776000e+03     3.000000           0
          BEVERAGES                   1.238601e+06  2092.231419           0
          BOOKS                       2.110000e+02     0.356419           0
...                                            ...          ...         ...
54        POULTRY                     3.553737e+04    60.029334           0
          PREPARED FOODS              4.279200e+04    72.283784           0
          PRODUCE                     3.786125e+05   639.548107           0
          SCHOOL AND OFFICE SUPPLIES  9.970000e+02     1.684122           0
          SEAFOOD                     1.082000e+03     1.827703           0


                                     max
store_nbr family
1         AUTOMOTIVE                   1
          BABY CARE                    0
          BEAUTY                       2
          BEVERAGES                   84
          BOOKS                        0
...                                   ..
54        POULTRY                     11
          PREPARED FOODS               7
          PRODUCE                     83
          SCHOOL AND OFFICE SUPPLIES   8
          SEAFOOD                      2

[1782 rows x 4 columns]

In [9]:
(retail.groupby(['store_nbr', 'family'])
     .agg(sales_mean=('sales', 'mean'),
          onpromotion_max=('onpromotion', 'max'))
)

                                       sales_mean  onpromotion_max
store_nbr family
1         AUTOMOTIVE                     4.263514                1
          BABY CARE                      0.000000                0
          BEAUTY                         3.000000                2
          BEVERAGES                   2092.231419               84
          BOOKS                          0.356419                0
...                                           ...              ...
54        POULTRY                       60.029334               11
          PREPARED FOODS                72.283784                7
          PRODUCE                      639.548107               83
          SCHOOL AND OFFICE SUPPLIES     1.684122                8
          SEAFOOD                        1.827703                2

[1782 rows x 2 columns]

In [13]:
premier_league = pd.read_csv('./assets/premier_league_games.csv')
premier_league.head()

,id,league_name,season,home_team,away_team,home_goals,away_goals
0,1,Premier League,1993/1994,Arsenal,Coventry,0,3
1,2,Premier League,1993/1994,Aston Villa,QPR,4,1
2,3,Premier League,1993/1994,Chelsea,Blackburn,1,2
3,4,Premier League,1993/1994,Liverpool,Sheffield Weds,2,0
4,5,Premier League,1993/1994,Man City,Leeds,1,1

In [19]:
useless_cols = ['league_name', 'away_team', 'id']

(premier_league.drop(useless_cols,axis = 1)
    .groupby(['season', 'home_team'], as_index=False)
    .agg('sum')
)

        season      home_team  home_goals  away_goals
0    1993/1994        Arsenal          25          15
1    1993/1994    Aston Villa          23          18
2    1993/1994      Blackburn          31          11
3    1993/1994        Chelsea          31          20
4    1993/1994       Coventry          23          17
..         ...            ...         ...         ...
659  2025/2026  Nott'm Forest          20          23
660  2025/2026     Sunderland          25          20
661  2025/2026      Tottenham          22          31
662  2025/2026       West Ham          27          30
663  2025/2026         Wolves          19          34

[664 rows x 4 columns]

In [20]:
(premier_league.drop(useless_cols, axis=1)
     .groupby(['season', 'home_team'], as_index=False)
     .agg(['sum', 'mean'])
)

        season      home_team home_goals           away_goals
                                     sum      mean        sum      mean
0    1993/1994        Arsenal         25  1.190476         15  0.714286
1    1993/1994    Aston Villa         23  1.095238         18  0.857143
2    1993/1994      Blackburn         31  1.476190         11  0.523810
3    1993/1994        Chelsea         31  1.476190         20  0.952381
4    1993/1994       Coventry         23  1.095238         17  0.809524
..         ...            ...        ...       ...        ...       ...
659  2025/2026  Nott'm Forest         20  1.052632         23  1.210526
660  2025/2026     Sunderland         25  1.315789         20  1.052632
661  2025/2026      Tottenham         22  1.157895         31  1.631579
662  2025/2026       West Ham         27  1.421053         30  1.578947
663  2025/2026         Wolves         19  1.000000         34  1.789474

[664 rows x 6 columns]

In [22]:
(premier_league.groupby(['season', 'home_team'],as_index=False)
 .agg({'home_goals': ['count', 'sum'],
       'away_goals': ['mean', 'max']})
)

        season      home_team home_goals     away_goals
                                   count sum       mean max
0    1993/1994        Arsenal         21  25   0.714286   3
1    1993/1994    Aston Villa         21  23   0.857143   2
2    1993/1994      Blackburn         21  31   0.523810   3
3    1993/1994        Chelsea         21  31   0.952381   3
4    1993/1994       Coventry         21  23   0.809524   2
..         ...            ...        ...  ..        ...  ..
659  2025/2026  Nott'm Forest         19  20   1.210526   3
660  2025/2026     Sunderland         19  25   1.052632   5
661  2025/2026      Tottenham         19  22   1.631579   4
662  2025/2026       West Ham         19  27   1.578947   5
663  2025/2026         Wolves         19  19   1.789474   4

[664 rows x 6 columns]

In [24]:
(premier_league.groupby(['season', 'home_team'],as_index=False)
 .agg(home_goal_sum=('home_goals', 'sum'),
      home_goal_mean=('home_goals', 'mean'))
)

        season      home_team  home_goal_sum  home_goal_mean
0    1993/1994        Arsenal             25        1.190476
1    1993/1994    Aston Villa             23        1.095238
2    1993/1994      Blackburn             31        1.476190
3    1993/1994        Chelsea             31        1.476190
4    1993/1994       Coventry             23        1.095238
..         ...            ...            ...             ...
659  2025/2026  Nott'm Forest             20        1.052632
660  2025/2026     Sunderland             25        1.315789
661  2025/2026      Tottenham             22        1.157895
662  2025/2026       West Ham             27        1.421053
663  2025/2026         Wolves             19        1.000000

[664 rows x 4 columns]