In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv('./assets/retail.csv')

mask = retail['family'].isin(['BABY CARE', 'AUTOMOTIVE', 'BEAUTY']) & retail['store_nbr'].isin(range(1,5))

small_retail = retail.loc[mask].sample(100, random_state=616)
small_retail.head()

             id        date  store_nbr      family  sales  onpromotion
217404  2163348  2016-05-02          1  AUTOMOTIVE    6.0            0
281556  2227500  2016-06-07          1  AUTOMOTIVE    3.0            0
505034  2450978  2016-10-10          3      BEAUTY   13.0            0
339670  2285614  2016-07-09          4   BABY CARE    0.0            0
263738  2209682  2016-05-28          1      BEAUTY    1.0            0

In [3]:
small_retail.pivot_table(columns='store_nbr',
                   index='family',
                   values='sales',
                   aggfunc='sum')

store_nbr      1     2      3     4
family
AUTOMOTIVE  32.0  58.0  147.0  29.0
BABY CARE    0.0   0.0    1.0   0.0
BEAUTY      22.0  41.0  269.0  20.0

In [4]:
small_retail.pivot_table(columns='store_nbr',
                   index='family',
                   values='sales',
                   aggfunc='sum',
                   margins=True)

store_nbr      1     2      3     4    All
family
AUTOMOTIVE  32.0  58.0  147.0  29.0  266.0
BABY CARE    0.0   0.0    1.0   0.0    1.0
BEAUTY      22.0  41.0  269.0  20.0  352.0
All         54.0  99.0  417.0  49.0  619.0

In [5]:
pm = pd.read_csv('./assets/premier_league_games.csv')
pm.head()

,id,league_name,season,home_team,away_team,home_goals,away_goals
0,1,Premier League,1993/1994,Arsenal,Coventry,0,3
1,2,Premier League,1993/1994,Aston Villa,QPR,4,1
2,3,Premier League,1993/1994,Chelsea,Blackburn,1,2
3,4,Premier League,1993/1994,Liverpool,Sheffield Weds,2,0
4,5,Premier League,1993/1994,Man City,Leeds,1,1

In [6]:
(pm.query("season > '2015/2016' and home_team in ['Arsenal', 'Chelsea', 'Everton']")
    .pivot_table(columns='season',
               index='home_team',
               values='home_goals',
               aggfunc='sum',
                margins=True)
)

season,2016/2017,2017/2018,2018/2019,2019/2020,2020/2021,2021/2022,2022/2023,2023/2024,2024/2025,2025/2026,All
home_team,,,,,,,,,,,
Arsenal,39,54,42,36,24,35,53,48,35,41,407
Chelsea,55,30,39,30,31,37,20,44,35,26,347
Everton,42,28,30,24,24,27,16,22,26,26,265
All,136,112,111,90,79,99,89,114,96,93,1019

In [7]:
small_retail.pivot_table(index='family',
                         columns='store_nbr',
                         values='sales',
                         aggfunc=('sum','mean'))

                mean                               sum
store_nbr          1         2          3      4     1     2      3     4
family
AUTOMOTIVE  3.555556  6.444444  13.363636  3.625  32.0  58.0  147.0  29.0
BABY CARE   0.000000  0.000000   0.200000  0.000   0.0   0.0    1.0   0.0
BEAUTY      2.444444  6.833333  15.823529  5.000  22.0  41.0  269.0  20.0

In [8]:
small_retail.pivot_table(columns='store_nbr',
                   index='family',
                   values='sales',
                   aggfunc='sum'
    ).style.background_gradient(cmap='RdYlGn', axis=None)

In [9]:
small_retail.pivot_table(columns='store_nbr',
                   index='family',
                   values='sales',
                   aggfunc='sum'
    ).style.background_gradient(cmap='RdYlGn', axis=1)

In [10]:
small_retail.pivot_table(columns='store_nbr',
                   index='family',
                   values='sales',
                   aggfunc='sum'
    ).style.background_gradient(cmap='RdYlGn', axis=0)

In [11]:
(pm.query("season > '2015/2016' and home_team in ['Arsenal', 'Chelsea', 'Everton']")
    .pivot_table(columns='season',
               index='home_team',
               values='home_goals',
               aggfunc='mean')
     .style.background_gradient(cmap='RdYlGn', axis=None)
)

In [12]:
(pm.query("season > '2015/2016' and home_team in ['Arsenal', 'Chelsea', 'Everton']")
    .pivot_table(columns='season',
               index='home_team',
               values='home_goals',
               aggfunc='mean')
     .style.background_gradient(cmap='RdYlGn', axis=1)
)

In [13]:
(pm.query("season > '2015/2016' and home_team in ['Arsenal', 'Chelsea', 'Everton']")
    .pivot_table(columns='season',
               index='home_team',
               values='home_goals',
               aggfunc='mean')
     .style.background_gradient(cmap='RdYlGn', axis=0)
)

In [16]:
premier_league = (pm.query("season > '2015/2016' and home_team in ['Arsenal', 'Chelsea', 'Everton']")
    .pivot_table(columns='season',
               index='home_team',
               values='home_goals',
               aggfunc='sum')
)
premier_league

season,2016/2017,2017/2018,2018/2019,2019/2020,2020/2021,2021/2022,2022/2023,2023/2024,2024/2025,2025/2026
home_team,,,,,,,,,,
Arsenal,39,54,42,36,24,35,53,48,35,41
Chelsea,55,30,39,30,31,37,20,44,35,26
Everton,42,28,30,24,24,27,16,22,26,26

In [21]:
pm2 = premier_league.reset_index()
pm2

season,home_team,2016/2017,2017/2018,2018/2019,2019/2020,2020/2021,2021/2022,2022/2023,2023/2024,2024/2025,2025/2026
0,Arsenal,39,54,42,36,24,35,53,48,35,41
1,Chelsea,55,30,39,30,31,37,20,44,35,26
2,Everton,42,28,30,24,24,27,16,22,26,26

In [29]:
pm2.melt(id_vars='home_team',
         value_vars=['2025/2026','2024/2025','2023/2024'],
         value_name='home_goals')

  home_team     season  home_goals
0   Arsenal  2025/2026          41
1   Chelsea  2025/2026          26
2   Everton  2025/2026          26
3   Arsenal  2024/2025          35
4   Chelsea  2024/2025          35
5   Everton  2024/2025          26
6   Arsenal  2023/2024          48
7   Chelsea  2023/2024          44
8   Everton  2023/2024          22